### ISSUE TITLE
Output as json

### ISSUE THREAD

**Issue by bjohas** [kgajera/hrvst-cli#1]
Hi @kgajera,

this is an amazing tool - thank you.

I wonder whether you'd consider alternative output formats? We're looking to process information retrieved from the API, and it would be really helpful to have an alternative output format. Output as json would be great, but also just tab-separated output would work. (At the moment I'm using `sed` to turn the existing output into tab-separated output.)

Many thanks for putting the tool together!

**Comment by kgajera** [comment]
This has been added in [v1.4.0](https://github.com/kgajera/hrvst-cli/releases/tag/v1.4.0).

**Comment by bjohas** [comment]
Thank you for implementing this - this is really incredibly useful for us!
