### ISSUE TITLE
Feature Request: add notes param to `hrvst stop`

### ISSUE THREAD

**Issue by adrian-livefront** [kgajera/hrvst-cli#4]
**What:**
It would be great to be able to add the `--notes` param to the `hrvst stop` command.
The expected behavior would be the same as with `hrvst start`.

**Why**
Sometimes when working on a task you end up doing more than you planned for within the project.
While `hrvst note` already provides functionality for that, a shortcut for the stop command would ensure nothing is forgotten at the end of the day.

**Comment by kgajera** [comment]
Just published version 1.7.0 that adds support for this. Docs are here: https://kgajera.github.io/hrvst-cli/cli/time-tracking#stop-a-timer

**Comment by adrian-livefront** [comment]
Awesome, thank you @kgajera, highly appreciated!
